// packages/@livestore/react/src/useStore.ts
import { exposeStoreForDebugging } from '@livestore/common'
import type { LiveStoreSchema } from '@livestore/common/schema'
import type { RegistryStoreOptions, Store } from '@livestore/livestore'
import type { Schema } from '@livestore/utils/effect'
import React from 'react'
import { useStoreRegistry } from './StoreRegistryContext.tsx'
import { useClientDocument } from './useClientDocument.ts'
import { useQuery } from './useQuery.ts'

/**
 * Returns a store instance augmented with hooks (`store.useQuery()` and `store.useClientDocument()`) for reactive queries.
 *
 * @example
 * ```tsx
 * function Issue() {
 *   // Suspends until loaded or returns immediately if already loaded
 *   const issueStore = useStore(issueStoreOptions('abc123'))
 *   const [issue] = issueStore.useQuery(queryDb(tables.issue.select()))
 *
 *   const toggleStatus = () =>
 *     issueStore.commit(
 *       issueEvents.issueStatusChanged({
 *         id: issue.id,
 *         status: issue.status === 'done' ? 'todo' : 'done',
 *       }),
 *     )
 *
 *   const preloadParentIssue = (issueId: string) =>
 *     storeRegistry.preload({
 *       ...issueStoreOptions(issueId),
 *       unusedCacheTime: 10_000,
 *     })
 *
 *   return (
 *     <>
 *       <h2>{issue.title}</h2>
 *       <button onClick={() => toggleStatus()}>Toggle Status</button>
 *       <button onMouseEnter={() => preloadParentIssue(issue.parentIssueId)}>Open Parent Issue</button>
 *     </>
 *   )
 * }
 * ```
 *
 * @remarks
 * - Suspends until the store is loaded.
 * - Store is cached by its `storeId` in the `StoreRegistry`. Multiple calls with the same `storeId` return the same store instance.
 * - Store is cached as long as it's being used, and after `unusedCacheTime` expires (default `60_000` ms in browser, `Infinity` in non-browser)
 * - Default store options can be configured in `StoreRegistry` constructor.
 * - Store options are only applied when the store is loaded. Subsequent calls with different options will not affect the store if it's already loaded and cached in the registry.
 *
 * @typeParam TSchema - The schema type for the store
 * @returns The loaded store instance augmented with React hooks
 * @throws unknown - store loading error or if called outside `<StoreRegistryProvider>`
 */
export const useStore = <
  TSchema extends LiveStoreSchema,
  TContext = {},
  TSyncPayloadSchema extends Schema.Schema<any> = typeof Schema.JsonValue,
>(
  options: RegistryStoreOptions<TSchema, TContext, TSyncPayloadSchema>,
): Store<TSchema, TContext> & ReactApi => {
  const storeRegistry = useStoreRegistry()

  // NOTE: retain() is called in useEffect (after render), while getOrLoadPromise() is called
  // in useMemo (during render). This creates a timing gap where with very short unusedCacheTime
  // values (e.g., 0), the store could theoretically be disposed before the effect fires.
  // In practice, this is not an issue with the default 60s cache time, but it becomes an issue when
  // `unusedCacheTime` is configured to values less than ~100ms.
  // See https://github.com/livestorejs/livestore/issues/916
  React.useEffect(() => storeRegistry.retain(options), [storeRegistry, options])

  const storeOrPromise = React.useMemo(() => storeRegistry.getOrLoadPromise(options), [storeRegistry, options])

  const store = storeOrPromise instanceof Promise ? React.use(storeOrPromise) : storeOrPromise

  exposeStoreForDebugging(store, options.debug?.instanceId ?? options.storeId)

  return withReactApi(store)
}

/**
 * React-specific methods added to the Store when used via React hooks.
 *
 * These methods are attached by `withReactApi()` and `useStore()`, allowing you
 * to call `store.useQuery()` and `store.useClientDocument()` directly on the
 * Store instance.
 */
export type ReactApi = {
  /** Hook version of query subscription—re-renders component when query result changes */
  useQuery: typeof useQuery
  /** Hook for reading and writing client-document tables with React state semantics */
  useClientDocument: typeof useClientDocument
}

/**
 * Augments a Store instance with React-specific methods (`useQuery`, `useClientDocument`).
 *
 * This is called automatically by `useStore()`. You typically don't need to call it
 * directly unless you're building custom integrations.
 *
 * @internal
 */
export const withReactApi = <TSchema extends LiveStoreSchema, TContext = {}>(
  store: Store<TSchema, TContext>,
): Store<TSchema, TContext> & ReactApi => {
  // @ts-expect-error TODO properly implement this
  store.useQuery = (queryable) => useQuery(queryable, { store })

  // @ts-expect-error TODO properly implement this
  store.useClientDocument = (table, idOrOptions, options) => useClientDocument(table, idOrOptions, options, { store })
  return store as Store<TSchema, TContext> & ReactApi
}

// packages/@livestore/solid/src/useStore.ts
import { every, when } from '@bigmistqke/solid-whenever'
import type { RowQuery, SessionIdSymbol } from '@livestore/common'
import { exposeStoreForDebugging } from '@livestore/common'
import type { LiveStoreSchema, State } from '@livestore/common/schema'
import type { Queryable, RegistryStoreOptions, Store } from '@livestore/livestore'
import type { Schema } from '@livestore/utils/effect'
import * as Solid from 'solid-js'
import { useStoreRegistry } from './StoreRegistryContext.tsx'
import { type UseClientDocumentResult, useClientDocument } from './useClientDocument.ts'
import { useQuery } from './useQuery.ts'
import { type AccessorMaybe, bypassSuspense, resolve } from './utils.tsx'

/**
 * Solid-specific methods added to the store Resource returned by `useStore()`.
 *
 * These methods handle the case where the store might not be loaded yet,
 * returning `undefined` or buffering locally until ready.
 */
export type SolidApi = {
  useClientDocument: {
    // case: table has default id → id is optional
    <
      TTableDef extends State.SQLite.ClientDocumentTableDef.Trait<
        any,
        any,
        any,
        {
          partialSet: boolean
          default: { id: string | SessionIdSymbol; value: any }
        }
      >,
    >(
      table: AccessorMaybe<TTableDef>,
      id?: AccessorMaybe<State.SQLite.ClientDocumentTableDef.DefaultIdType<TTableDef> | SessionIdSymbol>,
      options?: Partial<RowQuery.GetOrCreateOptions<TTableDef>>,
    ): UseClientDocumentResult<TTableDef>

    // case: table has no default id → id is required
    <
      TTableDef extends State.SQLite.ClientDocumentTableDef.Trait<
        any,
        any,
        any,
        { partialSet: boolean; default: { id: undefined; value: any } }
      >,
    >(
      table: AccessorMaybe<TTableDef>,
      id: AccessorMaybe<string | SessionIdSymbol>,
      options?: Partial<RowQuery.GetOrCreateOptions<TTableDef>>,
    ): UseClientDocumentResult<TTableDef>
  }
  useQuery<TQueryable extends Queryable<any>>(
    queryDef: AccessorMaybe<TQueryable>,
  ): Solid.Accessor<Queryable.Result<TQueryable> | undefined>
}

/**
 * Returns a store resource that suspends until the store is loaded.
 * The store is cached by its `storeId` in the `StoreRegistry`.
 *
 * @example
 * ```tsx
 * import { Suspense } from 'solid-js'
 *
 * function Issue(props: { issueId: string }) {
 *   const store = useStore(issueStoreOptions(props.issueId))
 *   const issues = store()?.useQuery(queryDb(tables.issue.select()))
 *
 *   return (
 *     <Show when={store()}>
 *       {(s) => <IssueView store={s()} />}
 *     </Show>
 *   )
 * }
 *
 * // With Suspense boundary
 * function App() {
 *   return (
 *     <Suspense fallback={<div>Loading...</div>}>
 *       <Issue issueId="abc123" />
 *     </Suspense>
 *   )
 * }
 * ```
 *
 * @remarks
 * - Suspends until the store is loaded when used within a Suspense boundary.
 * - Store is cached by its `storeId` in the `StoreRegistry`. Multiple calls with the same `storeId` return the same store instance.
 * - Store is cached as long as it's being used, and after `unusedCacheTime` expires (default `60_000` ms in browser, `Infinity` in non-browser)
 * - Default store options can be configured in `StoreRegistry` constructor.
 * - Store options are only applied when the store is loaded. Subsequent calls with different options will not affect the store if it's already loaded and cached in the registry.
 *
 * @typeParam TSchema - The schema type for the store
 * @typeParam TContext - User-defined context attached to the store
 * @typeParam TSyncPayloadSchema - Schema for the sync payload sent to the backend
 * @returns A Resource that resolves to the loaded store instance augmented with Solid hooks
 */
export const useStore = <
  TSchema extends LiveStoreSchema,
  TContext = {},
  TSyncPayloadSchema extends Schema.Schema<any> = typeof Schema.JsonValue,
>(
  options: AccessorMaybe<RegistryStoreOptions<TSchema, TContext, TSyncPayloadSchema>>,
): Solid.Resource<Store<TSchema, TContext>> & SolidApi => {
  const storeRegistry = useStoreRegistry()

  const [storeResource] = Solid.createResource(
    () => resolve(options),
    (opts) => {
      const id = opts.debug?.instanceId ?? opts.storeId

      const release = storeRegistry.retain(opts)
      Solid.onCleanup(release)

      const result = storeRegistry.getOrLoadPromise(opts)

      // Only suspend if store has not yet been initialized
      if (result instanceof Promise) {
        return result.then((store) => {
          exposeStoreForDebugging(store, id)
          return store
        })
      }

      exposeStoreForDebugging(result, id)

      return result
    },
  )

  return withSolidApi(storeResource)
}

/**
 * Augments a Store instance with Solid-specific methods (`useQuery`, `useClientDocument`).
 *
 * This is called automatically by `useStore()`. You typically don't need to call it
 * directly unless you're building custom integrations.
 *
 * @internal
 */
export const withSolidApi = <T extends Store<any, any> | Solid.Accessor<Store<any, any> | undefined>>(
  store: T,
): T & SolidApi => {
  return Object.assign(store, {
    useQuery(queryDef) {
      const latestStore = bypassSuspense(store)
      const queryMemo = Solid.createMemo(
        when(
          latestStore,
          (store) => useQuery(queryDef, { store }),
          (previous: Queryable.Result<any> | undefined) => previous,
        ),
      )

      return when(store, () => resolve(queryMemo()))
    },
    useClientDocument(table: any, id: any, options: any) {
      const [localState, setLocalState] = Solid.createSignal()
      const latestStore = bypassSuspense(store)

      const clientMemo = Solid.createMemo<UseClientDocumentResult<any> | undefined>(
        when(every(latestStore, table, id), ([store, table, id]) => {
          const client = useClientDocument(table, id, options, { store })

          const _localState = Solid.untrack(localState)
          if (_localState !== undefined) {
            client[1](_localState)
            setLocalState(undefined)
          }

          return client
        }),
      )

      // State accessor
      const state = when(clientMemo, ([get]) => get(), localState)

      // Setter
      const setState = when(clientMemo, ([, set], value) => set(value), setLocalState)

      // ID accessor: read store at read site (triggers Suspense if pending)
      const idAccessor = when(every(clientMemo, store), ([[, , id]]) => id())

      // Query accessor: read store at read site (triggers Suspense if pending)
      const queryAccessor = when(every(clientMemo, store), ([[, , , query]]) => query())

      return [state, setState, idAccessor, queryAccessor] as UseClientDocumentResult<any>
    },
  } as SolidApi)
}
